### ISSUE TITLE
OctoPi, error on CURL script.

### ISSUE THREAD

**Issue by JimBibe** [nvtkaszpir/prusa-connect-camera-script#5]
Hi, 

While running the screenshot, CURL, version of the script, I had to comment out the following lines in prusa-connect-camera.sh in order for the script to run:

#    --no-progress-meter \
#    --compressed \
#    -w "%{http_code}\n" \

Curl would complain about each option and it would not upload.  The error would read, "curl: option --no-progress-meter: is unknown" or "curl: option - --compressed: is unknown" or  curl: option - --w: is unknown"

pi@octopi:~/src/prusa-connect-camera-script $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by nvtkaszpir** [comment]
your system - and thus curl shipped with it - is ancient.
I'm surprised someone had it still alive.

Maybe I could add some detection and thus flag drop based on that?
